"""
queries/query_pick_detail_tracking_query_3.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Barcode singled out"
DESCRIPTION = (
    ""
)

# Block 1
SQL_BLOCK_1 = """
    SELECT *
    FROM PalletPlanningPickDetails d
    WHERE 
        (
            @barcode <> '' 
            AND d.barcode = @barcode
        )
        OR (
            @barcode = ''
            AND @warehouselocationid <> ''
            AND d.barcode IN (
                SELECT pd.barcode
                FROM PalletPlanningPickDetails pd
                WHERE pd.SourceLocation = @warehouselocationid
            )
        )
"""

_SQL_BLOCK_1_EXEC = """
    SELECT *
    FROM PalletPlanningPickDetails d
    WHERE 
        (
            ? <> '' 
            AND d.barcode = ?
        )
        OR (
            ? = ''
            AND ? <> ''
            AND d.barcode IN (
                SELECT pd.barcode
                FROM PalletPlanningPickDetails pd
                WHERE pd.SourceLocation = ?
            )
        )
"""


def run(barcode: str = "", warehouselocationid: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@barcode", "'" + str(barcode).replace("'", "''") + "'")\
    .replace("@warehouselocationid", "'" + str(warehouselocationid).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, (barcode, barcode, barcode, warehouselocationid, warehouselocationid,))
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
