"""
queries/query_automove_check_query_1.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Replen Diagnostic CTE"
DESCRIPTION = (
    ""
)

# Block 1
SQL_BLOCK_1 = """
    SELECT
            vid.PalletNumber,
            vid.WarehouseLocationId,
            vid.ProductId,
            vid.ProductionDate,
            vid.ShelfLifeDate,
            vid.Weight,
            vid.Qty,

            -- Order constraints
            ol.ItemMinProductionDate,
            ol.ItemMaxProductionDate,
            ol.ItemMinWeight,
            ol.ItemMaxWeight,
            ol.ItemMinSellByDate,

            -- Existing task / commitment checks
            dtExisting.DirectedTaskId AS ExistingTaskId,
            invCommitted.DeliveryNumber AS CommittedDelivery,

            ------------------------------------------------------------------
            -- RULE FLAGS (1 = FAIL, 0 = PASS)
            ------------------------------------------------------------------
            CASE 
                WHEN ol.ItemMinProductionDate IS NOT NULL 
                     AND vid.ProductionDate < ol.ItemMinProductionDate 
                THEN 1 ELSE 0 
            END AS Fail_MinProductionDate,

            CASE 
                WHEN ol.ItemMaxProductionDate IS NOT NULL 
                     AND vid.ProductionDate > ol.ItemMaxProductionDate 
                THEN 1 ELSE 0 
            END AS Fail_MaxProductionDate,

            CASE 
                WHEN ol.ItemMinWeight IS NOT NULL 
                     AND vid.Weight < ol.ItemMinWeight 
                THEN 1 ELSE 0 
            END AS Fail_MinWeight,

            CASE 
                WHEN ol.ItemMaxWeight IS NOT NULL 
                     AND vid.Weight > ol.ItemMaxWeight 
                THEN 1 ELSE 0 
            END AS Fail_MaxWeight,

            CASE
                WHEN ol.ItemMinSellByDate IS NOT NULL
                     AND vid.ShelfLifeDate < ol.ItemMinSellByDate
                THEN 1 ELSE 0
            END AS Fail_MinSellByDate,

            CASE
                WHEN vid.ShelfLifeDate < CONVERT(date, GETDATE())
                THEN 1 ELSE 0
            END AS Fail_Expired,

            CASE
                WHEN invCommitted.PalletNumber IS NOT NULL
                THEN 1 ELSE 0
            END AS Fail_CommittedToAnotherDelivery,

            CASE
                WHEN dtExisting.DirectedTaskId IS NOT NULL
                THEN 1 ELSE 0
            END AS Fail_TaskAlreadyExists

        FROM vwInventoryDetails vid WITH (READUNCOMMITTED)

        ------------------------------------------------------------------
        -- Replenishment Zone only (FIXED STRING_SPLIT)
        ------------------------------------------------------------------
        JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED)
            ON wal.LocationId = vid.WarehouseLocationId
           AND wal.ZoneId IN (
                SELECT CAST(ss.value AS INT)
                FROM WorkstationApplicationSettings was WITH (READUNCOMMITTED)
                CROSS APPLY STRING_SPLIT(was.Value, ',') ss
                WHERE was.PackageName = 'Protein.ShopFloor.Dashboard'
                  AND was.Code = 'ReplenishmentZones'
           )

        ------------------------------------------------------------------
        -- Delivery / Order context
        ------------------------------------------------------------------
        LEFT JOIN DeliveryLines dl WITH (READUNCOMMITTED)
            ON dl.ProductId = vid.ProductId
           AND dl.DeliveryNumber = @DeliveryNumber

        LEFT JOIN OrderLines ol WITH (READUNCOMMITTED)
            ON ol.OrderLineNumber = dl.OrderLineNumber
           AND ol.OrderNumber = (
                SELECT OrderNumber
                FROM Deliveries WITH (READUNCOMMITTED)
                WHERE DeliveryNumber = @DeliveryNumber
           )

        ------------------------------------------------------------------
        -- Existing commitment
        ------------------------------------------------------------------
        LEFT JOIN vwInventoryDetails invCommitted WITH (READUNCOMMITTED)
            ON invCommitted.PalletNumber = vid.PalletNumber
           AND invCommitted.DeliveryNumber IS NOT NULL

        ------------------------------------------------------------------
        -- Existing task
        ------------------------------------------------------------------
        LEFT JOIN DirectedTasks dtExisting WITH (READUNCOMMITTED)
            ON dtExisting.PalletNumber = vid.PalletNumber
           AND dtExisting.StatusId <> 7
"""

_SQL_BLOCK_1_EXEC = """
    SELECT
            vid.PalletNumber,
            vid.WarehouseLocationId,
            vid.ProductId,
            vid.ProductionDate,
            vid.ShelfLifeDate,
            vid.Weight,
            vid.Qty,

            -- Order constraints
            ol.ItemMinProductionDate,
            ol.ItemMaxProductionDate,
            ol.ItemMinWeight,
            ol.ItemMaxWeight,
            ol.ItemMinSellByDate,

            -- Existing task / commitment checks
            dtExisting.DirectedTaskId AS ExistingTaskId,
            invCommitted.DeliveryNumber AS CommittedDelivery,

            ------------------------------------------------------------------
            -- RULE FLAGS (1 = FAIL, 0 = PASS)
            ------------------------------------------------------------------
            CASE 
                WHEN ol.ItemMinProductionDate IS NOT NULL 
                     AND vid.ProductionDate < ol.ItemMinProductionDate 
                THEN 1 ELSE 0 
            END AS Fail_MinProductionDate,

            CASE 
                WHEN ol.ItemMaxProductionDate IS NOT NULL 
                     AND vid.ProductionDate > ol.ItemMaxProductionDate 
                THEN 1 ELSE 0 
            END AS Fail_MaxProductionDate,

            CASE 
                WHEN ol.ItemMinWeight IS NOT NULL 
                     AND vid.Weight < ol.ItemMinWeight 
                THEN 1 ELSE 0 
            END AS Fail_MinWeight,

            CASE 
                WHEN ol.ItemMaxWeight IS NOT NULL 
                     AND vid.Weight > ol.ItemMaxWeight 
                THEN 1 ELSE 0 
            END AS Fail_MaxWeight,

            CASE
                WHEN ol.ItemMinSellByDate IS NOT NULL
                     AND vid.ShelfLifeDate < ol.ItemMinSellByDate
                THEN 1 ELSE 0
            END AS Fail_MinSellByDate,

            CASE
                WHEN vid.ShelfLifeDate < CONVERT(date, GETDATE())
                THEN 1 ELSE 0
            END AS Fail_Expired,

            CASE
                WHEN invCommitted.PalletNumber IS NOT NULL
                THEN 1 ELSE 0
            END AS Fail_CommittedToAnotherDelivery,

            CASE
                WHEN dtExisting.DirectedTaskId IS NOT NULL
                THEN 1 ELSE 0
            END AS Fail_TaskAlreadyExists

        FROM vwInventoryDetails vid WITH (READUNCOMMITTED)

        ------------------------------------------------------------------
        -- Replenishment Zone only (FIXED STRING_SPLIT)
        ------------------------------------------------------------------
        JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED)
            ON wal.LocationId = vid.WarehouseLocationId
           AND wal.ZoneId IN (
                SELECT CAST(ss.value AS INT)
                FROM WorkstationApplicationSettings was WITH (READUNCOMMITTED)
                CROSS APPLY STRING_SPLIT(was.Value, ',') ss
                WHERE was.PackageName = 'Protein.ShopFloor.Dashboard'
                  AND was.Code = 'ReplenishmentZones'
           )

        ------------------------------------------------------------------
        -- Delivery / Order context
        ------------------------------------------------------------------
        LEFT JOIN DeliveryLines dl WITH (READUNCOMMITTED)
            ON dl.ProductId = vid.ProductId
           AND dl.DeliveryNumber = ?

        LEFT JOIN OrderLines ol WITH (READUNCOMMITTED)
            ON ol.OrderLineNumber = dl.OrderLineNumber
           AND ol.OrderNumber = (
                SELECT OrderNumber
                FROM Deliveries WITH (READUNCOMMITTED)
                WHERE DeliveryNumber = ?
           )

        ------------------------------------------------------------------
        -- Existing commitment
        ------------------------------------------------------------------
        LEFT JOIN vwInventoryDetails invCommitted WITH (READUNCOMMITTED)
            ON invCommitted.PalletNumber = vid.PalletNumber
           AND invCommitted.DeliveryNumber IS NOT NULL

        ------------------------------------------------------------------
        -- Existing task
        ------------------------------------------------------------------
        LEFT JOIN DirectedTasks dtExisting WITH (READUNCOMMITTED)
            ON dtExisting.PalletNumber = vid.PalletNumber
           AND dtExisting.StatusId <> 7
"""


def run(DeliveryNumber: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@DeliveryNumber", "'" + str(DeliveryNumber).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, (DeliveryNumber, DeliveryNumber,))
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols
        # ── Store result as named DataFrame for child queries ──────────────
        try:
            import pandas as _pd
            result.dataframe = {"ReplenPalletDiagnostics": _pd.DataFrame(
                [list(r) for r in rows], columns=cols
            )}
        except Exception:
            pass

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
