"""
queries/query_duplicate_inventory_fix_qa_statuses.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Fix Script — Delete Duplicate QA Statuses"
DESCRIPTION = (
    "Generates a SQL DELETE script to remove InventoryCasesQAStatuses records linked to duplicate inventory."
)

# Get Plant/Server
SQL_BLOCK_1 = """
    SELECT TOP 1
            p.Description AS PlantName,
            @@SERVERNAME  AS ServerName
        FROM Plants p WITH (READUNCOMMITTED)
        JOIN InventoryCases ic WITH (READUNCOMMITTED)
            ON ic.PlantCode = p.PlantCode
"""

_SQL_BLOCK_1_EXEC = """
    SELECT TOP 1
            p.Description AS PlantName,
            @@SERVERNAME  AS ServerName
        FROM Plants p WITH (READUNCOMMITTED)
        JOIN InventoryCases ic WITH (READUNCOMMITTED)
            ON ic.PlantCode = p.PlantCode
"""

# Get Duplicate IDs
SQL_BLOCK_2 = """
    SELECT
        'DELETE FROM InventoryCasesQaStatuses WHERE InventoryId = '
        + CAST(m.DuplicateInventoryId AS VARCHAR(20)) AS FixSQL,
        m.Barcode,
        m.DuplicateInventoryId
    FROM MaxInvIDResults m
    WHERE EXISTS (
        SELECT 1 FROM InventoryCasesQaStatuses q
        WHERE q.InventoryId = m.DuplicateInventoryId
    )
    ORDER BY m.DuplicateInventoryId
"""

_SQL_BLOCK_2_EXEC = """
    SELECT
        'DELETE FROM InventoryCasesQaStatuses WHERE InventoryId = '
        + CAST(m.DuplicateInventoryId AS VARCHAR(20)) AS FixSQL,
        m.Barcode,
        m.DuplicateInventoryId
    FROM MaxInvIDResults m
    WHERE EXISTS (
        SELECT 1 FROM InventoryCasesQaStatuses q
        WHERE q.InventoryId = m.DuplicateInventoryId
    )
    ORDER BY m.DuplicateInventoryId
"""


def run(df: dict | None = None) -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_2.strip()
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        # ── DataFrame → VALUES CTE injection ────────────────────────────────
        import re as _re
        from common import build_values_cte as _bvc
        _cte_parts = []
        for _df_key in ["MaxInvIDResults"]:
            if df and _df_key in df:
                _cte_parts.append(_bvc(df[_df_key], _df_key).removeprefix("WITH "))
        _cte_prefix = ("WITH " + ",\n".join(_cte_parts) + "\n") if _cte_parts else ""
        _sql_block_1 = _cte_prefix + _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1)
        while cursor.nextset():
            pass
        _sql_block_2 = _cte_prefix + _SQL_BLOCK_2_EXEC
        cursor.execute(_sql_block_2)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
