"""
queries/query_pick_detail_tracking_query_2.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "PalletPlanningPickDetails Info"
DESCRIPTION = (
    ""
)

# Block 1
SQL_BLOCK_1 = """
    SELECT *
    FROM PalletPlanningPickDetails d
    WHERE 
    (
        (@barcode = '' AND @warehouselocationid = '')

        OR

        (@barcode <> '' AND d.pickgroupid IN (
            SELECT pd.pickgroupid
            FROM PalletPlanningPickDetails pd
            WHERE pd.barcode = @barcode
        ))

        OR

        (@barcode = '' AND @warehouselocationid <> '' AND d.pickgroupid IN (
            SELECT pd.pickgroupid
            FROM PalletPlanningPickDetails pd
            WHERE pd.SourceLocation = @warehouselocationid
        ))
    )
    AND
    (
        @pickid = '' 
        OR d.PickGroupId IN (
            SELECT g.PickGroupId
            FROM PalletPlanningPickGroups g
            WHERE g.PickId = @pickid
        )
    )
"""

_SQL_BLOCK_1_EXEC = """
    SELECT *
    FROM PalletPlanningPickDetails d
    WHERE 
    (
        (? = '' AND ? = '')

        OR

        (? <> '' AND d.pickgroupid IN (
            SELECT pd.pickgroupid
            FROM PalletPlanningPickDetails pd
            WHERE pd.barcode = ?
        ))

        OR

        (? = '' AND ? <> '' AND d.pickgroupid IN (
            SELECT pd.pickgroupid
            FROM PalletPlanningPickDetails pd
            WHERE pd.SourceLocation = ?
        ))
    )
    AND
    (
        ? = '' 
        OR d.PickGroupId IN (
            SELECT g.PickGroupId
            FROM PalletPlanningPickGroups g
            WHERE g.PickId = ?
        )
    )
"""


def run(barcode: str = "", warehouselocationid: str = "", pickid: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@barcode", "'" + str(barcode).replace("'", "''") + "'")\
    .replace("@warehouselocationid", "'" + str(warehouselocationid).replace("'", "''") + "'")\
    .replace("@pickid", "'" + str(pickid).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, (barcode, warehouselocationid, barcode, barcode, barcode, warehouselocationid, warehouselocationid, pickid, pickid,))
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
