"""
queries/query_duplicate_inventory_detect.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Duplicate Inventory Detection"
DESCRIPTION = (
    "Finds barcodes with more than one active InventoryCase record. Excludes SHIPPED, SHIPRTN, ADJUST, and LVADJ from results."
)

# Build Temp Table
SQL_BLOCK_1 = """
    WITH MaxInvID AS (
        SELECT
            (SELECT TOP 1 warehouselocationid
             FROM InventoryCases ic2 WITH (READUNCOMMITTED)
             JOIN WarehouseAreaLocations wal2 WITH (READUNCOMMITTED) ON wal2.LocationId = ic2.WarehouseLocationId
             JOIN WarehouseAreas wa2 WITH (READUNCOMMITTED) ON wa2.WarehouseId = wal2.WarehouseId
                                    AND wa2.AreaId = wal2.AreaId
                                    AND wa2.IsAvailable = 1
             WHERE ic2.InventoryId = maxinvid
            ) AS CurrentLocation,
            cnt,
            maxinvid        AS CurrentInventoryId,
            x.InventoryId   AS DuplicateInventoryId,
            x.Barcode,
            x.WarehouseLocationId AS DuplicateLocation
        FROM (
            SELECT COUNT(1) OVER (PARTITION BY Barcode)    AS cnt,
                   MAX(InventoryId) OVER (PARTITION BY Barcode) AS maxinvid,
                   *
            FROM InventoryCases WITH (READUNCOMMITTED)
        ) x
        JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED) ON wal.LocationId = x.WarehouseLocationId
        JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
            ON wa.WarehouseId = wal.WarehouseId AND wa.AreaId = wal.AreaId
        WHERE cnt > 1
          AND x.WarehouseLocationId NOT IN (
                'SHIPPED','SHIPRTN','ADJUST','LVADJ',
                'HAM1','HAM2','BELLY','MHARV',
                'BLEND1','BLEND2','BLEND3','BLEND4','BLEND5','BLEND6','TB2'
          )
    )
    SELECT
        m.Barcode,
        m.cnt               AS DuplicateCount,
        m.CurrentInventoryId,
        m.CurrentLocation,
        m.DuplicateInventoryId,
        m.DuplicateLocation
    FROM MaxInvID m
    JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED) ON wal.LocationId = m.DuplicateLocation
    JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
        ON wa.WarehouseId = wal.WarehouseId AND wa.AreaId = wal.AreaId
    WHERE m.CurrentInventoryId <> m.DuplicateInventoryId
      AND m.DuplicateLocation NOT IN ('SHIPPED','SHIPRTN','ADJUST','LVADJ')
      AND (
            wa.IsAvailable = 1
            OR (
                EXISTS (SELECT 1 FROM InventoryCasesQaStatuses WHERE InventoryId = m.DuplicateInventoryId)
                AND EXISTS (SELECT 1 FROM InventoryCasesQaStatuses WHERE InventoryId = m.CurrentInventoryId)
            )
      )
    ORDER BY m.DuplicateLocation, m.Barcode
"""

_SQL_BLOCK_1_EXEC = """
    WITH MaxInvID AS (
        SELECT
            (SELECT TOP 1 warehouselocationid
             FROM InventoryCases ic2 WITH (READUNCOMMITTED)
             JOIN WarehouseAreaLocations wal2 WITH (READUNCOMMITTED) ON wal2.LocationId = ic2.WarehouseLocationId
             JOIN WarehouseAreas wa2 WITH (READUNCOMMITTED) ON wa2.WarehouseId = wal2.WarehouseId
                                    AND wa2.AreaId = wal2.AreaId
                                    AND wa2.IsAvailable = 1
             WHERE ic2.InventoryId = maxinvid
            ) AS CurrentLocation,
            cnt,
            maxinvid        AS CurrentInventoryId,
            x.InventoryId   AS DuplicateInventoryId,
            x.Barcode,
            x.WarehouseLocationId AS DuplicateLocation
        FROM (
            SELECT COUNT(1) OVER (PARTITION BY Barcode)    AS cnt,
                   MAX(InventoryId) OVER (PARTITION BY Barcode) AS maxinvid,
                   *
            FROM InventoryCases WITH (READUNCOMMITTED)
        ) x
        JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED) ON wal.LocationId = x.WarehouseLocationId
        JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
            ON wa.WarehouseId = wal.WarehouseId AND wa.AreaId = wal.AreaId
        WHERE cnt > 1
          AND x.WarehouseLocationId NOT IN (
                'SHIPPED','SHIPRTN','ADJUST','LVADJ',
                'HAM1','HAM2','BELLY','MHARV',
                'BLEND1','BLEND2','BLEND3','BLEND4','BLEND5','BLEND6','TB2'
          )
    )
    SELECT
        m.Barcode,
        m.cnt               AS DuplicateCount,
        m.CurrentInventoryId,
        m.CurrentLocation,
        m.DuplicateInventoryId,
        m.DuplicateLocation
    FROM MaxInvID m
    JOIN WarehouseAreaLocations wal WITH (READUNCOMMITTED) ON wal.LocationId = m.DuplicateLocation
    JOIN WarehouseAreas wa WITH (READUNCOMMITTED)
        ON wa.WarehouseId = wal.WarehouseId AND wa.AreaId = wal.AreaId
    WHERE m.CurrentInventoryId <> m.DuplicateInventoryId
      AND m.DuplicateLocation NOT IN ('SHIPPED','SHIPRTN','ADJUST','LVADJ')
      AND (
            wa.IsAvailable = 1
            OR (
                EXISTS (SELECT 1 FROM InventoryCasesQaStatuses WHERE InventoryId = m.DuplicateInventoryId)
                AND EXISTS (SELECT 1 FROM InventoryCasesQaStatuses WHERE InventoryId = m.CurrentInventoryId)
            )
      )
    ORDER BY m.DuplicateLocation, m.Barcode
"""


def run() -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols
        # ── Store result as named DataFrame for child queries ──────────────
        try:
            import pandas as _pd
            result.dataframe = {"MaxInvIDResults": _pd.DataFrame(
                [list(r) for r in rows], columns=cols
            )}
        except Exception:
            pass

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
