"""
queries/query_carcass_killgroup.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Kill Group"
DESCRIPTION = (
    "Looks up the KillGroups record using the kill group ID from the BackTag. Provides schedule group, purchase group, and head count."
)

# Kill Group Lookup
SQL_BLOCK_1 = """
    SELECT
            ScheduleGroup,
            PurchaseGroup,
            HeadCount
        FROM KillGroups WITH (READUNCOMMITTED)
        WHERE KillGroupId = @killgroupid
"""

_SQL_BLOCK_1_EXEC = """
    SELECT
            ScheduleGroup,
            PurchaseGroup,
            HeadCount
        FROM KillGroups WITH (READUNCOMMITTED)
        WHERE KillGroupId = @killgroupid
"""


def run(killgroupid: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@killgroupid", killgroupid)
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        _sql_block_1 = _sql_block_1.replace('@killgroupid', killgroupid)
        cursor.execute(_sql_block_1)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    # ── Extracted values for downstream queries ─────────────────────
        # ── Extracted: "ScheduleGroup" ────────────────────────────────────────────
        _col_ScheduleGroup = next(
            (i for i, c in enumerate(cols) if c.lower() == "schedulegroup"),
            None,
        )
        if _col_ScheduleGroup is not None:
            _vals_ScheduleGroup = [
                str(row[_col_ScheduleGroup])
                for row in rows
                if row[_col_ScheduleGroup] is not None
            ]
            result.extracted["ScheduleGroup"] = (
                _vals_ScheduleGroup[0] if len(_vals_ScheduleGroup) == 1 else _vals_ScheduleGroup
            )
        else:
            result.extracted["ScheduleGroup"] = ""
            result.add_message(
                "warning",
                f'[{TITLE}] Column \"ScheduleGroup\" not found in result set — '
                f'available columns: {", ".join(cols)}',
            )

    return result
