"""
queries/query_missing_carcasses_failed_transactions.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Failed Transactions"
DESCRIPTION = (
    "Checks for all failed transactions in the masterstaging table. Missing carcasses are often caused by failed MasterStaging transactions not posted to CPS."
)

# Detect Failed Transactions
SQL_BLOCK_1 = """
    select count(StagingId) as Count, PosterType
        from MasterStaging WITH (READUNCOMMITTED)
        where TransferStatus = -3
            and postertype in ('InventoryAdjustment',
                'OrderAcknowledgement',
                'InventoryStatus',
                'TrailerStatus',
                'OrderDetailChange',
                'ShipLoad',
                'PorkHotCarcass')
            and FailReason <> ''
        group by PosterType
"""

_SQL_BLOCK_1_EXEC = """
    select count(StagingId) as Count, PosterType
        from MasterStaging WITH (READUNCOMMITTED)
        where TransferStatus = -3
            and postertype in ('InventoryAdjustment',
                'OrderAcknowledgement',
                'InventoryStatus',
                'TrailerStatus',
                'OrderDetailChange',
                'ShipLoad',
                'PorkHotCarcass')
            and FailReason <> ''
        group by PosterType
"""


def run() -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
