"""
queries/query_load_wont_close_missing_trailer_capacity.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Missing Trailer Capacity"
DESCRIPTION = (
    "Checks if the trailer attached to the shipment has a trailer capacity assigned."
)

# Check Trailer Capacity
SQL_BLOCK_1 = """
    SELECT   s.trailerid
        FROM     shipments AS s WITH (READUNCOMMITTED)
        LEFT JOIN trailers AS t WITH (READUNCOMMITTED) ON s.trailerId = t.trailerId
        LEFT JOIN shipmentStopDeliveries AS ssd WITH (READUNCOMMITTED) ON s.shipmentNumber = ssd.shipmentNumber
        WHERE    ssd.DeliveryNumber = @delivery_number
            AND    (t.trailerCapacity IS NULL OR t.trailerCapacity = 0)
        ORDER BY s.shipmentNumber
"""

_SQL_BLOCK_1_EXEC = """
    SELECT   s.trailerid
        FROM     shipments AS s WITH (READUNCOMMITTED)
        LEFT JOIN trailers AS t WITH (READUNCOMMITTED) ON s.trailerId = t.trailerId
        LEFT JOIN shipmentStopDeliveries AS ssd WITH (READUNCOMMITTED) ON s.shipmentNumber = ssd.shipmentNumber
        WHERE    ssd.DeliveryNumber = ?
            AND    (t.trailerCapacity IS NULL OR t.trailerCapacity = 0)
        ORDER BY s.shipmentNumber
"""


def run(delivery_number: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@delivery_number", "'" + str(delivery_number).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, delivery_number)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
