"""
queries/query_inventory_cant_release_missing_qa_reason_codes.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Missing QA Reason Codes"
DESCRIPTION = (
    "Finds inventory on hold (QAStatusCode = 'HLD') with no QA reason code in InventoryCasesQaStatusReasons. These records will block release."
)

# Find Missing QA Reason Codes
SQL_BLOCK_1 = """
    -- Branch 1: The QAStatusCode row itself has a NULL QAReasonCode column.
        -- This means the hold was created without assigning a reason at the status level.
        SELECT s.InventoryId
        FROM InventoryCasesQaStatuses s WITH (READUNCOMMITTED)
        WHERE s.QAStatusCode  = 'HLD'
          AND s.QAReasonCode IS NULL

        UNION

        -- Branch 2: No matching row exists in the reasons child table at all.
        -- InventoryCasesQaStatusReasons stores the reason codes as separate records.
        -- A LEFT JOIN with a NULL check finds statuses that have no reasons linked.
        SELECT s.InventoryId
        FROM InventoryCasesQaStatuses s WITH (READUNCOMMITTED)
        LEFT JOIN InventoryCasesQaStatusReasons r WITH (READUNCOMMITTED)
            ON  r.PlantCode   = s.PlantCode
            AND r.InventoryId = s.InventoryId
        WHERE s.QAStatusCode = 'HLD'
          AND r.QAReasonCode IS NULL
"""

_SQL_BLOCK_1_EXEC = """
    -- Branch 1: The QAStatusCode row itself has a NULL QAReasonCode column.
        -- This means the hold was created without assigning a reason at the status level.
        SELECT s.InventoryId
        FROM InventoryCasesQaStatuses s WITH (READUNCOMMITTED)
        WHERE s.QAStatusCode  = 'HLD'
          AND s.QAReasonCode IS NULL

        UNION

        -- Branch 2: No matching row exists in the reasons child table at all.
        -- InventoryCasesQaStatusReasons stores the reason codes as separate records.
        -- A LEFT JOIN with a NULL check finds statuses that have no reasons linked.
        SELECT s.InventoryId
        FROM InventoryCasesQaStatuses s WITH (READUNCOMMITTED)
        LEFT JOIN InventoryCasesQaStatusReasons r WITH (READUNCOMMITTED)
            ON  r.PlantCode   = s.PlantCode
            AND r.InventoryId = s.InventoryId
        WHERE s.QAStatusCode = 'HLD'
          AND r.QAReasonCode IS NULL
"""


def run() -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
