"""
queries/query_pick_detail_tracking_query_1.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "PalletPlanningPickGroups Info"
DESCRIPTION = (
    ""
)

# Block 1
SQL_BLOCK_1 = """
    SELECT *
    FROM PalletPlanningPickGroups
    WHERE pickgroupid IN (
        SELECT PickGroupId
        FROM PalletPlanningPickDetails
        WHERE 
            (
                -- normal filters
                (@barcode <> '' AND barcode = @barcode)
                OR (@pickid <> '' AND PickId = @pickid)
            
                -- fallback to location ONLY if both are empty
                OR (
                    @barcode = '' 
                    AND @pickid = '' 
                    AND @warehouselocationid <> ''
                    AND SourceLocation = @warehouselocationid
                )
            )
    )
"""

_SQL_BLOCK_1_EXEC = """
    SELECT *
    FROM PalletPlanningPickGroups
    WHERE pickgroupid IN (
        SELECT PickGroupId
        FROM PalletPlanningPickDetails
        WHERE 
            (
                -- normal filters
                (? <> '' AND barcode = ?)
                OR (? <> '' AND PickId = ?)
            
                -- fallback to location ONLY if both are empty
                OR (
                    ? = '' 
                    AND ? = '' 
                    AND ? <> ''
                    AND SourceLocation = ?
                )
            )
    )
"""


def run(barcode: str = "", pickid: str = "", warehouselocationid: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@barcode", "'" + str(barcode).replace("'", "''") + "'")\
    .replace("@pickid", "'" + str(pickid).replace("'", "''") + "'")\
    .replace("@warehouselocationid", "'" + str(warehouselocationid).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, (barcode, barcode, pickid, pickid, barcode, pickid, warehouselocationid, warehouselocationid,))
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
