"""
queries/query_pick_detail_tracking_query_4.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Abort Reasons"
DESCRIPTION = (
    ""
)

# Block 1
SQL_BLOCK_1 = """
    ;WITH json_data AS (
        SELECT data
        FROM RawInterfaceData WITH (READUNCOMMITTED)
        WHERE ServiceId = 'IWSPickAbort'
          AND CreatedDate > DATEADD(day, -3, GETDATE())
          AND StatusId = 3
    ),
    results AS (
        SELECT 
            jt.UniqueIdentifier,
            jt.PickAbortId,
            jt.DeliveryNumber,
            jt.DeliveryLineNumber,
            jt.PickId,
            jt.PickGroupId,
            jt.LocationId,
            jt.InventoryType,
            jt.Barcode,
            jt.NeedReplacementBox,
            jt.AbortReasonId,
            jt.AbortReason
        FROM json_data AS jd
        CROSS APPLY OPENJSON(jd.data) WITH (
            UniqueIdentifier VARCHAR(MAX) '$.UniqueIdentifier',
            PickAbortId VARCHAR(MAX) '$.PickAbortId',
            DeliveryNumber VARCHAR(MAX) '$.DeliveryNumber',
            DeliveryLineNumber VARCHAR(MAX) '$.DeliveryLineNumber',
            PickId INT '$.PickId',
            PickGroupId INT '$.PickGroupId',
            LocationId VARCHAR(MAX) '$.LocationId',
            InventoryType VARCHAR(MAX) '$.InventoryType',
            Barcode VARCHAR(MAX) '$.Barcode',
            NeedReplacementBox VARCHAR(MAX) '$.NeedReplacementBox',
            AbortReasonId VARCHAR(MAX) '$.AbortReasonId',
            AbortReason VARCHAR(MAX) '$.AbortReason'
        ) AS jt
    )
    SELECT *
    FROM results
    WHERE 
        (@pickid = '' OR PickId = @pickid)
        AND (@warehouselocationid = '' OR LocationId = @warehouselocationid)
        AND (@barcode = '' OR Barcode = @barcode);
"""

_SQL_BLOCK_1_EXEC = """
    ;WITH json_data AS (
        SELECT data
        FROM RawInterfaceData WITH (READUNCOMMITTED)
        WHERE ServiceId = 'IWSPickAbort'
          AND CreatedDate > DATEADD(day, -3, GETDATE())
          AND StatusId = 3
    ),
    results AS (
        SELECT 
            jt.UniqueIdentifier,
            jt.PickAbortId,
            jt.DeliveryNumber,
            jt.DeliveryLineNumber,
            jt.PickId,
            jt.PickGroupId,
            jt.LocationId,
            jt.InventoryType,
            jt.Barcode,
            jt.NeedReplacementBox,
            jt.AbortReasonId,
            jt.AbortReason
        FROM json_data AS jd
        CROSS APPLY OPENJSON(jd.data) WITH (
            UniqueIdentifier VARCHAR(MAX) '$.UniqueIdentifier',
            PickAbortId VARCHAR(MAX) '$.PickAbortId',
            DeliveryNumber VARCHAR(MAX) '$.DeliveryNumber',
            DeliveryLineNumber VARCHAR(MAX) '$.DeliveryLineNumber',
            PickId INT '$.PickId',
            PickGroupId INT '$.PickGroupId',
            LocationId VARCHAR(MAX) '$.LocationId',
            InventoryType VARCHAR(MAX) '$.InventoryType',
            Barcode VARCHAR(MAX) '$.Barcode',
            NeedReplacementBox VARCHAR(MAX) '$.NeedReplacementBox',
            AbortReasonId VARCHAR(MAX) '$.AbortReasonId',
            AbortReason VARCHAR(MAX) '$.AbortReason'
        ) AS jt
    )
    SELECT *
    FROM results
    WHERE 
        (? = '' OR PickId = ?)
        AND (? = '' OR LocationId = ?)
        AND (? = '' OR Barcode = ?);
"""


def run(pickid: str = "", warehouselocationid: str = "", barcode: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@pickid", "'" + str(pickid).replace("'", "''") + "'")\
    .replace("@warehouselocationid", "'" + str(warehouselocationid).replace("'", "''") + "'")\
    .replace("@barcode", "'" + str(barcode).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, (pickid, pickid, warehouselocationid, warehouselocationid, barcode, barcode,))
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
