"""
queries/query_replenishment_check_replenishment_ineligible.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Replenishment - Ineligible Pallet Check"
DESCRIPTION = (
    "Finds pallets that match the product for the given pick face location but are blocked from replenishment, and explains why."
)

# Check Ineligible Pallets
SQL_BLOCK_1 = """
    -- Look up the ProductId configured for the given pick face location.
    -- PickFaceLocations maps a location code to the product it should hold.
    DECLARE @ProductId INT = (
        SELECT TOP 1 ProductId
        FROM PickFaceLocations WITH (READUNCOMMITTED)
        WHERE LocationId = @PickFaceLocation
    );

    -- CTE: find the most recent directed task for each pallet.
    -- DirectedTasks represent warehouse work instructions (e.g. move, pick, replenish).
    -- StatusId 7 = completed/closed task. Any other status means the task is still active.
    WITH LatestDirectedTask AS (
        SELECT dt.*
        FROM DirectedTasks dt WITH (READUNCOMMITTED)
        WHERE dt.CreatedDate = (
            SELECT MAX(dt2.CreatedDate)
            FROM DirectedTasks dt2 WITH (READUNCOMMITTED)
            WHERE dt2.PalletNumber = dt.PalletNumber
        )
    )

    SELECT
        vid.PalletNumber,
        -- Classify why each pallet cannot be replenished
        CASE
            -- Pallet is committed to a delivery — it cannot be replenished
            -- because it is already allocated for outbound shipment
            WHEN EXISTS (
                SELECT 1
                FROM vwInventoryDetails invCheck WITH (READUNCOMMITTED)
                WHERE invCheck.PalletNumber = vid.PalletNumber
                  AND invCheck.DeliveryNumber IS NOT NULL
            ) THEN 'Pallet is committed to a delivery'

            -- A non-completed directed task already exists for this pallet.
            -- The system will not create a second task until the first is resolved.
            WHEN EXISTS (
                SELECT 1
                FROM LatestDirectedTask dt
                WHERE dt.PalletNumber = vid.PalletNumber
                  AND dt.StatusId NOT IN (7)
            ) THEN 'Active directed task already exists for pallet'

            -- Pallet appears ineligible but neither known condition applies.
            -- This may indicate a sort order issue or a new blocking condition.
            ELSE 'Unknown — pallet should be eligible, check sort order'
        END AS Reason

    FROM vwInventoryDetails vid WITH (READUNCOMMITTED)
    LEFT JOIN LatestDirectedTask dt ON dt.PalletNumber = vid.PalletNumber

    WHERE
        -- Only look at pallets carrying the product configured for this pick face
        vid.ProductId = @ProductId

        -- Pallet must be in a replenishment zone (configured in WorkstationApplicationSettings).
        -- ReplenishmentZones is a comma-separated list of ZoneIds stored in the settings table.
        AND vid.WarehouseLocationId IN (
            SELECT LocationId
            FROM WarehouseAreaLocations
            WHERE ZoneId IN (
                SELECT CAST(intValues.value AS INT)
                FROM WorkstationApplicationSettings WITH (READUNCOMMITTED)
                CROSS APPLY STRING_SPLIT(value, ',') AS intValues
                WHERE PackageName = 'Protein.ShopFloor.Dashboard'
                  AND Code = 'ReplenishmentZones'
            )
        )

        -- Exclude pallets that ARE fully eligible — we only want the blocked ones.
        -- A pallet is eligible when: not committed to a delivery AND no active directed task.
        AND NOT (
            NOT EXISTS (
                SELECT 1
                FROM vwInventoryDetails invCheck WITH (READUNCOMMITTED)
                WHERE invCheck.PalletNumber = vid.PalletNumber
                  AND invCheck.DeliveryNumber IS NOT NULL
            )
            AND (
                dt.PalletNumber IS NULL
                OR dt.StatusId IN (7)
            )
        )

    ORDER BY vid.PalletNumber;
"""

_SQL_BLOCK_1_EXEC = """
    -- Look up the ProductId configured for the given pick face location.
    -- PickFaceLocations maps a location code to the product it should hold.
    DECLARE ? INT = (
        SELECT TOP 1 ProductId
        FROM PickFaceLocations WITH (READUNCOMMITTED)
        WHERE LocationId = ?
    );

    -- CTE: find the most recent directed task for each pallet.
    -- DirectedTasks represent warehouse work instructions (e.g. move, pick, replenish).
    -- StatusId 7 = completed/closed task. Any other status means the task is still active.
    WITH LatestDirectedTask AS (
        SELECT dt.*
        FROM DirectedTasks dt WITH (READUNCOMMITTED)
        WHERE dt.CreatedDate = (
            SELECT MAX(dt2.CreatedDate)
            FROM DirectedTasks dt2 WITH (READUNCOMMITTED)
            WHERE dt2.PalletNumber = dt.PalletNumber
        )
    )

    SELECT
        vid.PalletNumber,
        -- Classify why each pallet cannot be replenished
        CASE
            -- Pallet is committed to a delivery — it cannot be replenished
            -- because it is already allocated for outbound shipment
            WHEN EXISTS (
                SELECT 1
                FROM vwInventoryDetails invCheck WITH (READUNCOMMITTED)
                WHERE invCheck.PalletNumber = vid.PalletNumber
                  AND invCheck.DeliveryNumber IS NOT NULL
            ) THEN 'Pallet is committed to a delivery'

            -- A non-completed directed task already exists for this pallet.
            -- The system will not create a second task until the first is resolved.
            WHEN EXISTS (
                SELECT 1
                FROM LatestDirectedTask dt
                WHERE dt.PalletNumber = vid.PalletNumber
                  AND dt.StatusId NOT IN (7)
            ) THEN 'Active directed task already exists for pallet'

            -- Pallet appears ineligible but neither known condition applies.
            -- This may indicate a sort order issue or a new blocking condition.
            ELSE 'Unknown — pallet should be eligible, check sort order'
        END AS Reason

    FROM vwInventoryDetails vid WITH (READUNCOMMITTED)
    LEFT JOIN LatestDirectedTask dt ON dt.PalletNumber = vid.PalletNumber

    WHERE
        -- Only look at pallets carrying the product configured for this pick face
        vid.ProductId = ?

        -- Pallet must be in a replenishment zone (configured in WorkstationApplicationSettings).
        -- ReplenishmentZones is a comma-separated list of ZoneIds stored in the settings table.
        AND vid.WarehouseLocationId IN (
            SELECT LocationId
            FROM WarehouseAreaLocations
            WHERE ZoneId IN (
                SELECT CAST(intValues.value AS INT)
                FROM WorkstationApplicationSettings WITH (READUNCOMMITTED)
                CROSS APPLY STRING_SPLIT(value, ',') AS intValues
                WHERE PackageName = 'Protein.ShopFloor.Dashboard'
                  AND Code = 'ReplenishmentZones'
            )
        )

        -- Exclude pallets that ARE fully eligible — we only want the blocked ones.
        -- A pallet is eligible when: not committed to a delivery AND no active directed task.
        AND NOT (
            NOT EXISTS (
                SELECT 1
                FROM vwInventoryDetails invCheck WITH (READUNCOMMITTED)
                WHERE invCheck.PalletNumber = vid.PalletNumber
                  AND invCheck.DeliveryNumber IS NOT NULL
            )
            AND (
                dt.PalletNumber IS NULL
                OR dt.StatusId IN (7)
            )
        )

    ORDER BY vid.PalletNumber;
"""


def run(ProductId: str = "", PickFaceLocation: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@ProductId", "'" + str(ProductId).replace("'", "''") + "'")\
    .replace("@PickFaceLocation", "'" + str(PickFaceLocation).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, (ProductId, PickFaceLocation, ProductId,))
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
