"""
queries/query_carcass_hot.py

# AUTO-GENERATED BY QUERY BUILDER — DO NOT EDIT MANUALLY
# To modify this query, reopen it in the Query Builder
# (⚙  Query Builder in the sidebar), edit and regenerate.
"""

from common import QueryResult
from db import db
TITLE       = "Hot Carcass"
DESCRIPTION = (
    "Looks up the HotCarcasses record for this carcass ID. Provides side, kill dates, and approval details."
)

# Hot Carcass Lookup
SQL_BLOCK_1 = """
    SELECT TOP 1
            Side,
            KillDate,
            BackTagKillDate,
            ApprovedBy,
            ApprovedDate
        FROM HotCarcasses WITH (READUNCOMMITTED)
        WHERE BackTagCarcassId = @carcass_id
        ORDER BY KillDate DESC
"""

_SQL_BLOCK_1_EXEC = """
    SELECT TOP 1
            Side,
            KillDate,
            BackTagKillDate,
            ApprovedBy,
            ApprovedDate
        FROM HotCarcasses WITH (READUNCOMMITTED)
        WHERE BackTagCarcassId = ?
        ORDER BY KillDate DESC
"""


def run(carcass_id: str = "") -> QueryResult:
    result = QueryResult()
    result.sql = SQL_BLOCK_1.strip()\
    .replace("@carcass_id", "'" + str(carcass_id).replace("'", "''") + "'")
    result.add_message("info", f"[{TITLE}] Running...")

    try:
        cursor = db.conn.cursor()

        if getattr(db, "cancelled", False):
            result.status  = "error"
            result.headline = "Query cancelled — disconnected."
            return result

        _sql_block_1 = _SQL_BLOCK_1_EXEC
        cursor.execute(_sql_block_1, carcass_id)
        rows = cursor.fetchall()
        cols = [col[0] for col in cursor.description]
        result.cols = cols

    except Exception as exc:
        result.success  = False
        result.status   = "error"
        result.headline = f"{TITLE}: Query error — {exc}"
        result.add_message("error", result.headline)
        return result
    finally:
        if cursor:
            cursor.close()

    if not rows:
        result.status   = "ok"
        result.headline = "No records found."
        result.add_message("success", f"  ✔ {TITLE}: {result.headline}")
    else:
        result.status   = "issues_found"
        result.headline = f"{len(rows)} record(s) found."
        result.data     = [" | ".join(str(v) for v in row) for row in rows]
        result.add_message("warning", f"  ⚠ {result.headline}")

    return result
